### ISSUE TITLE
Parallax transition should not be applied until first scroll

### ISSUE THREAD

**Issue by jmikrut** [trouble/react-ui-components#2]
Currently, the parallax transition is applied immediately, which makes the component "slide" into position on first page load.  The transition should not be set until the first scroll event has fired, or similar, to avoid this initial sliding.

**Comment by jacobsfletch** [comment]
@jmikrut Ah, I do see what you mean. Move the `transition` css into a conditional.

**Comment by jmikrut** [comment]
I don't think this is fixed as I still see the `BackgroundCircles` jumping into their first parallax position within the Custer site.

Can you confirm? Is this a separate issue?

**Comment by jmikrut** [comment]
I noticed that in Custer, CSS is applied directly to `Parallax` components within the `app.scss` file. This may be the cause of the issue?

![image](https://user-images.githubusercontent.com/6651896/68596230-e26b1580-0468-11ea-9bae-0b7ffc21bbb9.png)

**Comment by jacobsfletch** [comment]
@jmikrut It was fixed until the technique was modified

**Comment by jacobsfletch** [comment]
@jmikrut This ticket can be re-opened as it has since come back

**Comment by jacobsfletch** [comment]
^^^ To be more specific, the component has become css agnostic since its initial iteration, meaning it no longer applies any styles of its own -- so the fix here, at first glance, will be to add a class for the developer to tie into when the `hasScrolled` prop is truthy.

**Comment by jacobsfletch** [comment]
See https://github.com/trouble/react-parallax/commit/449a54501c506858b2d99cb8248ef4d7133a83fe
